### ISSUE TITLE
[오타신고] Wiki ▸ API Reference ▸ Core ▸ Selections

### ISSUE THREAD

**Issue by ppeeou** [zziuni/d3#2]
오타가 난 것 같아 이슈 남깁니다...

# selection.remove()
변경 전
>현제 문서의 현재 선택물에서 문서요소를 제거한다. 

변경 후
>현재 문서의 현재 선택물에서 문서요소를 제거한다. 

문서에 다시 다시 추가하는 방법이 없기 때문에 일반적으로 문서요소를 제거한 후에는 그 선택물 사용을 멈춰야 한다. ( 추가는 바로 앞에서 설명한 append와 insert 참고)

**Comment by zziuni** [comment]
감사합니다~ :)
